apiVersion: v1
kind: Service
metadata:
  name: nginx-gateway-service
  namespace: default
spec:
  selector:
    app: nginx-gateway
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 32470

